Adding support for child gauges
beethovenxfi/beethovenx-backend pull request #346
Opened 2023-05-17 09:45 UTC by gmbronco

* BAL rewards in new L2 gauges, AKA child chain gauges are stored as `inflation_rate` variable on the contract. In the gauge syncing workflow we fetch them for all the gauges via multicall and we in the DB as a reward token.

2023-05-18 07:19 UTC, franzns commented on prisma/schema.prisma
> +    version             Int                             @default(1)
needs to be added to pool.prisma not schema.prisma

schema.prisma is generated by `yarn prisma-merge`

2023-05-22 09:14 UTC, danielmkm requested changes

2023-05-22 09:14 UTC, danielmkm commented on modules/token/token.service.ts
> +    public async getVeBalTotalSupply(): Promise<string> {
wouldn't really add this here, doesn't make a lot of sense

2023-05-22 09:14 UTC, danielmkm commented on modules/subgraphs/veBal-locks-subgraph/veBal-locks-subgraph.service.ts
> +    // TODO needs proper paging, currently <3000 locks so it works
Would not leave this as a todo, just gonna come back and bite you in the ass later, as you'll forget it

2023-05-22 09:14 UTC, danielmkm commented on modules/subgraphs/veBal-locks-subgraph/veBal-locks-subgraph.service.ts
> +    // TODO needs proper paging, currently <3000 locks so it works
use `id_gt` as a means to safely paginate

2023-05-22 09:14 UTC, danielmkm commented on modules/token/token.gql
> +    tokenGetVeBalTotalSupply: AmountHumanReadable!
dont put this here

2023-05-22 09:14 UTC, danielmkm commented on modules/token/token.prisma
> +    totalSupply         String?
nope

2023-05-22 09:14 UTC, danielmkm commented on modules/token/token.resolvers.ts
> +        tokenGetVeBalTotalSupply: async (parent, {}, context) => {
move this into its own module

2023-05-22 09:14 UTC, danielmkm commented on modules/user/lib/user-sync-wallet-balance.service.ts
> +    async syncVeBalBalances() {
would also pull this out into its own

2023-05-22 12:06 UTC, franzns commented
Thanks, I will create a dedicated veBAL module for all of it.

2023-05-23 11:10 UTC, danielmkm approved these changes

2023-05-23 11:47 UTC, merged